### ISSUE TITLE
can't docker-compose production

### ISSUE THREAD

**Issue by xfouloux** [guy0090/LostArkLogs#1]
Hi,

i wanted to try out your project, but i get this error for site and api when i try to compose up

```
-  Building for production...
 ERROR  Failed to compile with 1 error2:56:18 AM


/app/src/log-parsing/lib/objects.ts
   64:16  error  Replace `⏎········e.type·===·EntityType.PLAYER·&&⏎········Object.keys(e.skills).length·>·0⏎······` with `e.type·===·EntityType.PLAYER·&&·Object.keys(e.skills).length·>·0`  prettier/prettier
  305:16  error  Replace `⏎········e.type·===·EntityType.PLAYER·&&⏎········Object.keys(e.skills).length·>·2⏎······` with `e.type·===·EntityType.PLAYER·&&·Object.keys(e.skills).length·>·2`  prettier/prettier

✖ 2 problems (2 errors, 0 warnings)
  2 errors and 0 warnings potentially fixable with the `--fix` option.


You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
 ERROR  Error: Build failed with errors.
Error: Build failed with errors.
    at /app/node_modules/@vue/cli-service/lib/commands/build/index.js:207:23
    at /app/node_modules/webpack/lib/webpack.js:148:8
    at /app/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/app/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.shutdown (/app/node_modules/webpack/lib/Cache.js:150:23)
    at /app/node_modules/webpack/lib/Compiler.js:1225:15
    at Hook.eval [as callAsync] (eval at create (/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/app/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.close (/app/node_modules/webpack/lib/Compiler.js:1218:23)
```

Thanks

**Comment by xfouloux** [comment]
https://github.com/guy0090/LostArkLogs/blob/c7c02f6153efbfc951d5fcad1fbf03c4be0e2db0/frontend/src/log-parsing/lib/objects.ts#L61-L69

https://github.com/guy0090/LostArkLogs/blob/c7c02f6153efbfc951d5fcad1fbf03c4be0e2db0/frontend/src/log-parsing/lib/objects.ts#L302-L311

i managed to fix things by adding 

```
RUN npm run lint -- --fix
```
in the frontend Dockerfile between lines like this
```
RUN npm install
RUN npm run lint -- --fix
RUN npm run build
```

**Comment by guy0090** [comment]
Fixed. Looks like I forgot to lint before that commit/push. Also added the run step to auto lint if this happens again (in bda5aaba5900ed8ea0ed4f4c5859f502291ff32d). 
Cheers
